#!/bin/sh

cd rust
cargo b \
--target x86_64-apple-ios \
--target aarch64-apple-ios \
--target  x86_64-apple-darwin
cargo lipo --release
cbindgen src/lib.rs -l c > rust.h

cp rust.h ../hello-rust/include
cp target/universal/release/librust.a ../hello-rust/libs

cd ../hello-rust && xcodebuild
