#!/bin/sh
cd rust
cargo b \
--target x86_64-apple-ios \
--target aarch64-apple-ios \
--target aarch64-apple-ios-sim
--target  x86_64-apple-darwin || \
    rustup component add rust-src --toolchain nightly-aarch64-apple-darwin || \
    rustup target add aarch64-apple-ios-sim aarch64-apple-ios aarch64-apple-darwin x86_64-apple-ios x86_64-apple-darwin
cargo +nightly build -Z build-std --target aarch64-apple-ios-sim
cargo lipo --release
cbindgen src/lib.rs -l c > rust.h

cp rust.h ../hello-rust/include
cp target/universal/release/librust.a ../hello-rust/libs
cp target/aarch64-apple-ios-sim/debug/librust.a ../hello-rust/libs/librust-sim.a

cd ../hello-rust && xcodebuild
